# Generated by Django 2.2.4 on 2019-08-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subImages',
        ),
        migrations.AddField(
            model_name='product',
            name='firstImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/{name}/'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/{name}/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thirdImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/{name}/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('HF', 'HF'), ('WA', 'WA')], default='MOBILES', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/{name}/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cart_products',
            field=models.ManyToManyField(blank=True, to='backend.Product'),
        ),
        migrations.DeleteModel(
            name='Product_Description',
        ),
        migrations.DeleteModel(
            name='Product_Image',
        ),
    ]
