# Generated by Django 2.2.4 on 2019-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190804_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='firstImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/{self.name}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/{self.name}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/{self.name}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thirdImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/{self.name}'),
        ),
    ]
