# Generated by Django 2.2.4 on 2019-08-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190804_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('stars', models.IntegerField()),
                ('description', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='firstImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thirdImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product_Review'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product_Review'),
        ),
    ]
