# Generated by Django 2.2.4 on 2019-08-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product_Category'),
        ),
    ]
