# Generated by Django 2.2.4 on 2019-08-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190804_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='product_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_products',
            field=models.ManyToManyField(blank=True, related_name='order', to='backend.Product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cart_products',
            field=models.ManyToManyField(blank=True, related_name='cart', to='backend.Product'),
        ),
        migrations.CreateModel(
            name='Product_Cart_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.BooleanField(blank=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Profile')),
            ],
        ),
    ]
