# Generated by Django 2.2.4 on 2019-08-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190805_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Cart_Value',
        ),
    ]
