# Generated by Django 2.2.4 on 2019-08-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_delete_product_cart_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainShowcase1', models.ImageField(upload_to='', verbose_name='posters/showcase/')),
                ('mainShowcase2', models.ImageField(upload_to='', verbose_name='posters/showcase/')),
                ('mainShowcase3', models.ImageField(upload_to='', verbose_name='posters/showcase/')),
                ('mainShowcase4', models.ImageField(upload_to='', verbose_name='posters/showcase/')),
            ],
        ),
    ]
