# Generated by Django 2.2.4 on 2019-08-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20190830_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='varients',
            field=models.ManyToManyField(blank=True, null=True, related_name='products_varients', to='backend.Product'),
        ),
    ]
