# Generated by Django 2.2.4 on 2019-08-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_product_varients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alsoBuy',
            field=models.ManyToManyField(blank=True, related_name='similar_varients', to='backend.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='varients',
            field=models.ManyToManyField(blank=True, related_name='color_varients', to='backend.Product'),
        ),
    ]
