# Generated by Django 2.2.4 on 2019-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20190831_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='name',
            field=models.CharField(choices=[('MOBILE', 'MOBILE'), ('HEADPHONE', 'HEADPHONE'), ('WATCH', 'WATCH')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='product_category',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='product_category',
            name='subCategory',
            field=models.ManyToManyField(to='backend.Product_Category'),
        ),
    ]
