# Generated by Django 2.2.4 on 2019-08-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20190831_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='subCategory',
            field=models.ManyToManyField(blank=True, to='backend.Product_Category'),
        ),
    ]
