# Generated by Django 2.2.4 on 2019-09-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
